#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/izzo/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/izzo/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/izzo/Documenti/Ilaria/KTH/Ricerca/Alexander_Cahlin/Our_model/x86_64/.libs/libnrnmech.so" "$@"
