function [fitresult, gof] = createFit(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'activation sigmoid' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Feb-2018 10:32:33


%% Fit: 'activation sigmoid'.
[xData, yData] = prepareCurveData( x , y );

% Set up fittype and options.
ft = fittype( '1./(1+exp(k*(x-v)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.157613081677548 0.970592781760616];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'activation sigmoid' );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x', 'activation sigmoid', 'Location', 'NorthEast' );
% Label axes
xlabel x
ylabel y
grid on


