function [fitresult, gof] = taufits2(x, y, blurb1)
%CREATEFIT(X,Y,BLURB1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%      Weights : blurb1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Mar-2018 19:11:12


%% Fit: 'untitled fit 1'.
[xData, yData, weights] = prepareCurveData( x, y, blurb1 );

% Set up fittype and options.
ft = fittype( '-0.03-C*(1-exp((-x+shift)/taum)).^3.*exp((-x+shift)/tauh)', 'independent', 'x', 'dependent', 'y' );

% [bottom,index]=min(yData);
% pks=findpeaks(yData(1:index));
% bottomlimit=pks.loc(end);
% pksafter=findpeaks(yData(index:end));
% afterall=pksafter.loc(1);
bottomlimit=0.3;
afterall=3;


excludedPoints = (xData < bottomlimit) | (xData > afterall);
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.996134716626885 0.0781755287531837 0.442678269775446 0.106652770180584];
opts.Weights = weights;
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'y vs. x with blurb1', 'Excluded y vs. x with blurb1', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel x
ylabel y
grid on


