function [fitresult, gof] = taufits(ttest, yTest)
%CREATEFIT(TTEST,YTEST)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : ttest
%      Y Output: yTest
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Mar-2018 18:38:45


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( ttest, yTest );

% Set up fittype and options.
ft = fittype( '-0.03-C*(1-exp((-x+shift)/taum)).^3.*exp((-x+shift)/tauh)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = (xData < 0.3) | (xData > 8);
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [1.8 -Inf 1 0];
opts.StartPoint = [0.351659507062997 0.568823660872193 0.186872604554379 0.489764395788231];
opts.Upper = [2.2 Inf 2 1];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'yTest vs. ttest', 'Excluded yTest vs. ttest', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel ttest
ylabel yTest
grid on


