function [fitresult, gof] = TauFitter(AOIt, AOII, weightI)
%CREATEFIT(AOIT,AOII,WEIGHTI)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : AOIt
%      Y Output: AOII
%      Weights : weightI
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-Mar-2018 12:40:28


%% Fit: 'untitled fit 1'.
[xData, yData, weights] = prepareCurveData( AOIt, AOII, weightI );

% Set up fittype and options.
ft = fittype( 'a-b*(1-exp(-x+shift)/t1)^3*exp((-x+shift)/t2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-0.5 0 -500 0 0];
opts.StartPoint = [0.547215529963803 0.138624442828679 0.149294005559057 0.257508254123736 0.840717255983663];
opts.Upper = [0.5 10 500 100 100];
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'AOII vs. AOIt with weightI', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel AOIt
ylabel AOII
grid on


